# Generated by Django 4.0.4 on 2022-06-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.CharField(default='', max_length=250),
        ),
    ]
