# Generated by Django 4.0.4 on 2022-07-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
