# Generated by Django 4.0.4 on 2022-07-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_promo_active_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='until',
            field=models.DateTimeField(),
        ),
    ]
