# Generated by Django 4.0.4 on 2022-07-16 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_promo_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronic_address',
            name='email',
        ),
        migrations.RemoveField(
            model_name='electronic_address',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='electronic_address',
            name='url',
        ),
    ]
