# Generated by Django 4.0.4 on 2022-07-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_remove_electronic_address_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.ImageField(upload_to='backgrounds')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
