# Generated by Django 4.0.4 on 2022-07-28 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0008_homebackground'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased', models.BooleanField(default=True)),
                ('price', models.FloatField(default=0.0)),
                ('qty', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.category')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.service')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
