# Generated by Django 4.0.4 on 2022-07-30 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0010_alter_cart_purchased'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='bill_address1',
            new_name='ship_address3',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='bill_address2',
            new_name='ship_address4',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bill_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bill_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bill_phone1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bill_postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bill_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_weight',
        ),
        migrations.RemoveField(
            model_name='order',
            name='special_instruction',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='order_date',
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='dropoff_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='dropoff_time_slot',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_place_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time_slot',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='promo_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usercart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('open', 'open'), ('pending', 'pending'), ('shipped', 'shipped'), ('cancelled', 'cancelled'), ('refund', 'refund'), ('partial_refund', 'partial_refund'), ('delivered', 'delivered'), ('declined', 'declined'), ('confirmed', 'confirmed'), ('processing', 'processing')], default='open', max_length=50),
        ),
    ]
