# Generated by Django 4.0.4 on 2022-07-30 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_rename_category_id_cart_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='models.order'),
            preserve_default=False,
        ),
    ]
