# Generated by Django 4.0.4 on 2022-07-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_paymentintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='client_secret',
            field=models.CharField(default='', max_length=90),
            preserve_default=False,
        ),
    ]
