# Generated by Django 4.0.4 on 2022-08-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_order_addressdetail_order_detail_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='refund',
            field=models.BooleanField(default=False),
        ),
    ]
