# Generated by Django 4.0.4 on 2022-08-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_paymentintent_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='refund_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
