# Generated by Django 4.0.4 on 2022-08-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0019_notification_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('body', models.CharField(max_length=500)),
                ('accountsid', models.CharField(max_length=150)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.CharField(blank=True, max_length=150, null=True)),
                ('sent_to', models.CharField(max_length=50)),
                ('sent_from', models.CharField(max_length=50)),
                ('uri', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
