# Generated by Django 4.0.4 on 2022-08-09 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0021_servicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='servicetype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_type', to='models.servicetype'),
            preserve_default=False,
        ),
    ]
