# Generated by Django 4.0.2 on 2022-08-16 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0022_service_servicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='picture',
            field=models.ImageField(default='/media/files/coatgrey-03.png', upload_to='typeImage'),
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(default='', max_length=100)),
                ('recipient_type', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=10)),
                ('status_message', models.CharField(max_length=10)),
                ('recipients', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1000)),
                ('recipient_type', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=10)),
                ('status_message', models.CharField(max_length=10)),
                ('recipients', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
