# Generated by Django 4.0.2 on 2022-08-12 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0022_service_servicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetype',
            name='picture',
            field=models.ImageField(default='', upload_to='typeImage'),
            preserve_default=False,
        ),
    ]
