# Generated by Django 4.0.2 on 2022-08-12 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0023_servicetype_active_servicetype_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='created_by',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
