# Generated by Django 4.0.2 on 2022-08-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0025_userverification_messagerecord_emailrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerecord',
            name='sid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
