# Generated by Django 4.0.2 on 2022-08-20 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0026_messagerecord_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='promousage',
            name='promo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='used_by', to='models.promo'),
            preserve_default=False,
        ),
    ]
