# Generated by Django 4.0.2 on 2022-08-21 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0028_remove_order_promo_notification_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='servicetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='services', to='models.servicetype'),
        ),
    ]
