# Generated by Django 4.0.2 on 2022-09-27 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0030_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronic_address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electronic_address', to=settings.AUTH_USER_MODEL),
        ),
    ]
