# Generated by Django 4.0.2 on 2022-09-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0032_alter_emailrecord_status_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerecord',
            name='sid',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='messagerecord',
            name='status_message',
            field=models.TextField(),
        ),
    ]
