# Generated by Django 4.0.2 on 2022-11-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0036_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebackground',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('open', 'open'), ('in-progress', 'in-progress'), ('cancelled', 'cancelled'), ('declined', 'declined'), ('refunded', 'refunded'), ('completed', 'completed')], default='open', max_length=50),
        ),
    ]
