# Generated by Django 4.0.4 on 2022-05-14 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('picture', models.ImageField(upload_to='categoryImage')),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=100)),
                ('lname', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('ordernotecheck', models.BooleanField(default=False)),
                ('order_amount', models.DecimalField(decimal_places=4, max_digits=65)),
                ('promo', models.CharField(blank=True, max_length=100, null=True)),
                ('order_status', models.CharField(choices=[('pending', 'pending'), ('shipped', 'shipped'), ('cancelled', 'cancelled'), ('refund', 'refund'), ('partial_refund', 'partial_refund'), ('delivered', 'delivered'), ('declined', 'declined'), ('confirmed', 'confirmed'), ('processing', 'processing')], default='pending', max_length=50)),
                ('deleted', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('special_instruction', models.TextField(blank=True, null=True)),
                ('err_message', models.TextField(blank=True, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('ship_date', models.DateTimeField(blank=True, null=True, verbose_name='ShipmentDate')),
                ('ship_address1', models.TextField(blank=True, null=True)),
                ('ship_address2', models.TextField(blank=True, null=True)),
                ('ship_phone1', models.CharField(blank=True, max_length=50, null=True)),
                ('ship_postal_code', models.CharField(blank=True, max_length=6, null=True)),
                ('ship_city', models.CharField(blank=True, max_length=50, null=True)),
                ('ship_state', models.CharField(blank=True, max_length=50, null=True)),
                ('ship_country', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_address1', models.TextField(blank=True, null=True)),
                ('bill_address2', models.TextField(blank=True, null=True)),
                ('bill_phone1', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_postal_code', models.CharField(blank=True, max_length=6, null=True)),
                ('bill_city', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_state', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_country', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=65, null=True)),
                ('shipping_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('shipping_weight', models.CharField(blank=True, max_length=254, null=True)),
                ('shipping_number', models.CharField(blank=True, max_length=254, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.CharField(max_length=500)),
                ('unit_price', models.FloatField(default=0.0, max_length=10)),
                ('bottom_heading', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_attributes_available', models.BooleanField(default=False)),
                ('sku', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('shipment_duration', models.CharField(blank=True, max_length=254, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='models.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=450)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productattributes', to='models.service')),
            ],
        ),
        migrations.CreateModel(
            name='Postal_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.TextField(blank=True, null=True)),
                ('address2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Home', 'Home'), ('Billing', 'Billing'), ('Shipping', 'Shipping')], default='Home', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=65)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('card_holder_name', models.CharField(blank=True, max_length=254, null=True)),
                ('last4digit', models.CharField(blank=True, max_length=5, null=True)),
                ('card_type', models.CharField(blank=True, max_length=20, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=5, null=True)),
                ('process_type', models.CharField(blank=True, max_length=25, null=True)),
                ('trans_type', models.CharField(blank=True, max_length=15, null=True)),
                ('auth_code', models.CharField(blank=True, max_length=254, null=True)),
                ('response_data', models.TextField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=254, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=254, null=True)),
                ('parent_ref_id', models.CharField(blank=True, max_length=254, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=65, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('discount', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=65, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=65, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='models.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.service')),
            ],
        ),
        migrations.CreateModel(
            name='Electronic_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
