# Generated by Django 4.0.4 on 2022-05-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_category_newsletter_order_service_serviceattribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='', upload_to='categoryicons'),
            preserve_default=False,
        ),
    ]
