# Generated by Django 4.0.4 on 2022-05-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.ImageField(upload_to='files')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
