# Generated by Django 4.0.4 on 2022-05-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_postcode_weekday_timeslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='shipment_duration',
            new_name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
