# Generated by Django 4.0.4 on 2022-05-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_rename_shipment_duration_service_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcode',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
