# Generated by Django 4.0.4 on 2022-05-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_postcode_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcode',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
