# Generated by Django 4.0.4 on 2022-06-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_emailconfig_phoneconfig_schedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='ScheduleConfig',
        ),
    ]
