# Generated by Django 4.0.4 on 2022-06-15 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
