# Generated by Django 4.0.2 on 2022-09-25 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0023_servicetype_active_servicetype_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promo',
        ),
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_notification', to='models.order'),
        ),
        migrations.AddField(
            model_name='promousage',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='used_by', to='models.promo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='servicetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='services', to='models.servicetype'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='picture',
            field=models.ImageField(upload_to='typeImage'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=250)),
                ('line2', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('province', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
                ('postcode', models.CharField(max_length=250)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
